# Generated by Django 3.0.6 on 2020-05-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminosity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luminosity',
            name='type',
            field=models.CharField(max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='luminosity',
            name='value',
            field=models.IntegerField(verbose_name='tipo_de_terreno'),
        ),
    ]
