# Generated by Django 3.0.6 on 2020-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminosity', '0003_auto_20200513_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='luminosity',
            name='latitude',
            field=models.IntegerField(default=0, verbose_name='latitud_del_lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luminosity',
            name='length',
            field=models.IntegerField(default=0, verbose_name='longitud_del_lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luminosity',
            name='terrain',
            field=models.CharField(default=0, max_length=25, verbose_name='tipo_de_terreno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='luminosity',
            name='value',
            field=models.IntegerField(verbose_name='valor'),
        ),
    ]
