# Generated by Django 3.0.6 on 2020-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminosity', '0004_auto_20200513_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luminosity',
            name='latitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='latitud_del_lugar'),
        ),
        migrations.AlterField(
            model_name='luminosity',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='longitud_del_lugar'),
        ),
        migrations.AlterField(
            model_name='luminosity',
            name='terrain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tipo_de_terreno'),
        ),
    ]
